[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# Need permission to read files
fs_permissions = [
    {access = "read", path = "data/standard/mock_rollup_proof_data_3x2.dat"},
    {access = "read", path = "data/standard/mock_proof.dat"}
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config